### ISSUE TITLE
Affininty Designer: Icon mask not antialiased

### ISSUE THREAD

**Issue by hpohlmeyer** [bjango/Bjango-Templates#1]
I found a bug in the Affinity Designer templates: The Fill layers, used to color the icon mask background do not get antialiased.
## Steps to reproduce
1. Hide the labels group 
2. Now you should already see it.
3. Turn on 1x pixel preview and zoom in to make it more obvious.
## Workarounds
- Color the icon masks layer directly and delete the two backgrounds inside
- Replace the two fill layers with colored vector rectangles
## Bug Report

I also made a [bug report](https://affinity.serif.com/forum/index.php?/topic/25635-missing-antialiasing-on-fill-layers/) in the Serif Forums, but I think that bug will have a low priority, because there seems to be no way to create fill layer other than by importing a photoshop document.

**Comment by hpohlmeyer** [comment]
The Affinity Designer staff cleared it up:
This is intended for performance reasons, you can enable correct clipping by going to:

**Affinity Designer Preferences → Performance → Check _Use precise clipping_**

**Comment by marcedwards** [comment]
@hpohlmeyer Thanks! I’ve seen this and wondered about it myself. I’ve now turned on Use precise clipping. 👍
