### ISSUE TITLE
Request for Adobe XD icon templates

### ISSUE THREAD

**Issue by megaroeny** [bjango/Bjango-Templates#4]
Hey Marc! I'd actually be willing to help out with this, if you're interested! I'm solely using Adobe XD now for work.

**Comment by marcedwards** [comment]
Hello! Yep, I’m hoping to get XD templates done soon. We’ve just finished a big launch, so I should get some spare time in the coming weeks. I’d love you feedback, when they’re ready.

**Comment by megaroeny** [comment]
Definitely!

**Comment by marcedwards** [comment]
The Greyprint templates have been updated with XD support.

https://github.com/bjango/Greyprint

Moving onto the app icon templates next. :)

**Comment by marcedwards** [comment]
XD is still missing some essential features I would like for the icon templates. That makes it difficult to build templates I’d be happy with. I might wait until XD has better symbols before proceeding.

**Comment by marcedwards** [comment]
December 2019 update: XD is still missing the features needed to make the templates. Gah.

**Comment by megaroeny** [comment]
Honestly if you want @marcedwards  you can close this is you want. I stopped using XS after I left my previous job over 2 years ago lol! Now totally dedicated to Figma.

**Comment by marcedwards** [comment]
It would be great to have, and I’ll build it if I can. I just need symbols to handle multiple instances that are different sizes, where the master symbol can be updated and the instances reflect the changes. XD still can’t do that.

**Comment by marcedwards** [comment]
It’s looking very likely that Adobe XD is going to be replaced by Adobe Figma. Closing this for now.
